use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use rusqlite::{Connection, params};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

#[derive(Parser)]
#[command(name = "dpcp", about = "Dynamic Port Configuration Protocol — host-central port broker for git worktrees")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Allocate ports for a worktree and write .dpcp.env
    Allocate {
        /// Absolute path to the worktree
        worktree: PathBuf,
        /// Services with their default ports, e.g. postgres:5432 redis:6379
        #[arg(required = true)]
        services: Vec<String>,
        /// Where to write the env file (defaults to <worktree>/.dpcp.env)
        #[arg(long)]
        env_file: Option<PathBuf>,
    },
    /// Release all port allocations for a worktree
    Release {
        /// Absolute path to the worktree
        worktree: PathBuf,
    },
    /// List all current allocations
    List,
    /// Remove allocations for worktrees whose paths no longer exist
    Gc,
}

fn db_path() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(home).join(".dpcp.sqlite")
}

fn open_db() -> Result<Connection> {
    let path = db_path();
    let conn = Connection::open(&path)
        .with_context(|| format!("failed to open {}", path.display()))?;
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS allocations (
            worktree TEXT NOT NULL,
            service  TEXT NOT NULL,
            port     INTEGER NOT NULL,
            PRIMARY KEY (worktree, service)
        );
        CREATE UNIQUE INDEX IF NOT EXISTS idx_port ON allocations(port);",
    )?;
    Ok(conn)
}

fn port_is_bound(port: u16) -> bool {
    use std::net::TcpListener;
    TcpListener::bind(("0.0.0.0", port)).is_err()
}

/// Find the lowest port >= start_port not in the dpcp database and not bound on the host.
fn next_free_port(conn: &Connection, start_port: u16) -> Result<u16> {
    let mut port = start_port;
    loop {
        let in_db: bool = conn.query_row(
            "SELECT COUNT(*) > 0 FROM allocations WHERE port = ?1",
            params![port],
            |row| row.get(0),
        )?;
        if !in_db && !port_is_bound(port) {
            return Ok(port);
        }
        port = port.checked_add(1).context("port space exhausted")?;
    }
}

fn cmd_allocate(
    worktree: &Path,
    services: &[String],
    env_file: Option<&Path>,
) -> Result<()> {
    let worktree = worktree
        .canonicalize()
        .with_context(|| format!("worktree path does not exist: {}", worktree.display()))?;
    let worktree_str = worktree.to_string_lossy();

    let conn = open_db()?;

    // Parse service:port pairs
    let mut requests: Vec<(String, u16)> = Vec::new();
    for spec in services {
        let (name, default_port) = spec
            .split_once(':')
            .with_context(|| format!("expected service:port, got '{spec}'"))?;
        let default_port: u16 = default_port
            .parse()
            .with_context(|| format!("invalid port in '{spec}'"))?;
        requests.push((name.to_string(), default_port));
    }

    let mut assignments: HashMap<String, u16> = HashMap::new();

    for (service, default_port) in &requests {
        // Re-use existing allocation for this worktree+service if present
        let existing: Option<u16> = conn
            .query_row(
                "SELECT port FROM allocations WHERE worktree = ?1 AND service = ?2",
                params![worktree_str.as_ref(), service],
                |row| row.get(0),
            )
            .ok();

        let port = if let Some(p) = existing {
            p
        } else {
            let p = next_free_port(&conn, *default_port)?;
            conn.execute(
                "INSERT INTO allocations (worktree, service, port) VALUES (?1, ?2, ?3)",
                params![worktree_str.as_ref(), service, p],
            )?;
            p
        };
        assignments.insert(service.clone(), port);
    }

    // Write env file
    let env_path = env_file
        .map(PathBuf::from)
        .unwrap_or_else(|| worktree.join(".dpcp.env"));

    let mut lines: Vec<String> = vec![
        "# Generated by dpcp — do not edit by hand".to_string(),
        format!("# Worktree: {worktree_str}"),
    ];
    for (service, default_port) in &requests {
        let port = assignments[service];
        let key = format!("{}_PORT", service.to_uppercase().replace('-', "_"));
        lines.push(format!("{key}={port}"));
        if *default_port != port {
            lines.push(format!(
                "# ^ {service} default {default_port}, allocated {port}"
            ));
        }
    }
    lines.push(String::new());

    std::fs::write(&env_path, lines.join("\n"))
        .with_context(|| format!("failed to write {}", env_path.display()))?;

    println!("Wrote {}", env_path.display());
    for (service, default_port) in &requests {
        let port = assignments[service];
        let flag = if *default_port == port { "" } else { " (reassigned)" };
        println!("  {service}: {port}{flag}");
    }

    Ok(())
}

fn cmd_release(worktree: &Path) -> Result<()> {
    // Canonicalize if the path still exists; fall back to the raw path for already-deleted worktrees.
    let canonical = worktree.canonicalize().unwrap_or_else(|_| worktree.to_path_buf());
    let worktree_str = canonical.to_string_lossy();
    let conn = open_db()?;
    let deleted = conn.execute(
        "DELETE FROM allocations WHERE worktree = ?1",
        params![worktree_str.as_ref()],
    )?;
    println!("Released {deleted} allocation(s) for {worktree_str}");
    Ok(())
}

fn cmd_list() -> Result<()> {
    let conn = open_db()?;
    let mut stmt = conn.prepare(
        "SELECT worktree, service, port FROM allocations ORDER BY worktree, service",
    )?;
    let rows: Vec<(String, String, u16)> = stmt
        .query_map([], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)))?
        .collect::<rusqlite::Result<_>>()?;

    if rows.is_empty() {
        println!("No allocations.");
        return Ok(());
    }

    let mut current_wt = String::new();
    for (worktree, service, port) in &rows {
        if *worktree != current_wt {
            println!("{worktree}");
            current_wt = worktree.clone();
        }
        println!("  {service}: {port}");
    }
    Ok(())
}

fn cmd_gc() -> Result<()> {
    let conn = open_db()?;
    let mut stmt =
        conn.prepare("SELECT DISTINCT worktree FROM allocations")?;
    let worktrees: Vec<String> = stmt
        .query_map([], |row| row.get(0))?
        .collect::<rusqlite::Result<_>>()?;

    let mut freed = 0usize;
    for wt in worktrees {
        if !Path::new(&wt).exists() {
            let n = conn.execute(
                "DELETE FROM allocations WHERE worktree = ?1",
                params![wt],
            )?;
            println!("GC: removed {n} allocation(s) for missing worktree {wt}");
            freed += n;
        }
    }
    if freed == 0 {
        println!("Nothing to collect.");
    } else {
        println!("Freed {freed} total allocation(s).");
    }
    Ok(())
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::Allocate { worktree, services, env_file } => {
            cmd_allocate(&worktree, &services, env_file.as_deref())
        }
        Commands::Release { worktree } => cmd_release(&worktree),
        Commands::List => cmd_list(),
        Commands::Gc => cmd_gc(),
    }
}
